require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

# platform :ios, '13.0'  # Update to a higher deployment target

target 'TempProject' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  # Add react-native-google-maps and react-native-maps from node_modules
  pod 'react-native-google-maps', :path => '../node_modules/react-native-maps'
  pod 'react-native-maps', :path => '../node_modules/react-native-maps'

  target 'TempProjectTests' do
    inherit! :complete
    # Pods for testing
  end

  post_install do |installer|
    # Ensure the react_native_post_install is called
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false
    )

    # Bypass the problematic privacy_manifest_utils to avoid the nil 'each' method error
    if defined?(privacy_manifest_utils) && privacy_manifest_utils.respond_to?(:add_aggregated_privacy_manifest)
      privacy_manifest_utils.add_aggregated_privacy_manifest(installer)
    end
  end
end
